site_name: My Docs
site_url: https://github.com/UmikaSoft/
site_description: Project documentation with Markdown.
site_author: MkDocs Team

repo_url: https://github.com/UmikaSoft/LiteProtocol
edit_uri: blob/master/docs/

dev_addr: "127.0.0.1:8082"
